### ISSUE TITLE
Updating versions in `setup.py`

### ISSUE THREAD

**Issue by OmAximani0** [crowdin/crowdin-api-client-python#103]
Since we updated the dependency versions, I think we should also update the `setup.py` accordingly 

https://github.com/crowdin/crowdin-api-client-python/blob/52767cf9cf0f6de444e3abe999b5ae599dd6dd1e/setup.py#L71-L78

**Comment by andrii-bodnar** [comment]
@OmAximani0 thanks for the suggestion!

**Comment by andrii-bodnar** [comment]
Would you like to create a PR?

**Comment by OmAximani0** [comment]
> Would you like to create a PR?

Yes, I would like to

**Comment by OmAximani0** [comment]
Do we need to update the `classifier`s also in `setup.py` ?
https://github.com/crowdin/crowdin-api-client-python/blob/52767cf9cf0f6de444e3abe999b5ae599dd6dd1e/setup.py#L58-L65

**Comment by andrii-bodnar** [comment]
@OmAximani0 what's the purpose if this array?

**Comment by OmAximani0** [comment]
I think its used to show the supported versions of python, you can read more [here](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#classifiers)

**Comment by OmAximani0** [comment]
I also suggest that the please review the `setup.py` once again cause there some more changes can be found such as `python_requires`
