### ISSUE TITLE
Add project_id property to client to set it once and skip this parameter in functions

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#123]
### Discussed in https://github.com/crowdin/crowdin-api-client-python/discussions/71

<div type='discussions-op-text'>

<sup>Originally posted by **xabk** March  1, 2023</sup>
Hello!

I feel like most of the time, the client is used to work with one project but it still requires you to pass `project_id` into every single project-related function.

It would be great if the client itself had a `project_id` property that could be set and used by the functions under the hood.

What do you guys think?</div>

**Comment by OmAximani0** [comment]
Hi @andrii-bodnar , Yes this make sense, and if client mostly work with single project we should introduce `project_id` as property.

**Comment by andrii-bodnar** [comment]
Hi @OmAximani0, would you like to be assigned here?

**Comment by OmAximani0** [comment]
@andrii-bodnar Yes I would love to do this, Assigned it to me
