### ISSUE TITLE
Fix Unit tests for Python 3.12

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#127]
I added version 3.12 to the CI/CD pipeline in #126 and some tests failed.

https://github.com/crowdin/crowdin-api-client-python/actions/runs/6453647001/job/17517596970

We need to fix these tests to run successfully on 3.12.

**Comment by rsk2** [comment]
Hi @andrii-bodnar, I am interested in working on this issue. It looks like using `assert_called_once_with` will fix the test.
