### ISSUE TITLE
Applications API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#130]
Crowdin has recently added new endpoints for managing custom applications. Support for these endpoints is missing in this Crowdin API client.

We need to add support for the following endpoints:

- [Get Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.get)
- [Update or Restore Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.put)
- [Add Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.post)
- [Delete Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.delete)
- [Edit Application Data](https://developer.crowdin.com/api/v2/#operation/api.applications.api.patch)

**Comment by portalghost** [comment]
Hi, I would like to work on that. If i may

**Comment by m-inaam** [comment]
Hi @andrii-bodnar, can I work on this issue along with @portalghost . Is it possible?

**Comment by kisharnath** [comment]
If you do not mind can  I look into it?

**Comment by andrii-bodnar** [comment]
@kisharnath great, thank you!

**Comment by kisharnath** [comment]
Can you give more information about the problem?

**Comment by andrii-bodnar** [comment]
@kisharnath,

The Crowdin API client provides methods that essentially call Crowdin's APIs.

This makes it much easier for other developers to make calls to Crowdin's APIs, as the client abstracts a lot of the work required.

Feel free to take a look at the existing code. You'll find methods that send a request to various API methods.

So just like that the client needs methods that can handle calls to Crowdin's "Applications" APIs listed in the issue description.
