### ISSUE TITLE
Report Settings Template: add the `isPublic` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#131]
The Report Settings Template API now supports the ability to create public templates. We need to add support for the `isPublic` property to this Crowdin API client.

**References:**

- [Add Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.post)
- [Get Report Settings Template](https://developer.crowdin.com/api/v2/#operation/api.projects.reports.settings-templates.get) (response)

**Comment by m-inaam** [comment]
Hi @andrii-bodnar, can you please assign me this issue

**Comment by andrii-bodnar** [comment]
Hi @m-inaam, assigned. Thank you!

**Comment by m-inaam** [comment]
Can please give more details as to where exactly these templates need to added? I mean by which file can I find `isPublic ` property in Crowdin API client.

**Comment by andrii-bodnar** [comment]
@m-inaam please refer to the [reports](https://github.com/crowdin/crowdin-api-client-python/tree/main/crowdin_api/api_resources/reports) API

**Comment by OmAximani0** [comment]
@andrii-bodnar I want to work on this
