### ISSUE TITLE
Source Files: add the `context` property support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#132]
The Source Files API now supports the possibility to specify the `context` for the whole file. We need to add support for the `context` property to this Crowdin API client.

**References:**

- [Add File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.post)
- [Edit File](https://developer.crowdin.com/api/v2/#operation/api.projects.files.patch)
- [Get file](https://developer.crowdin.com/api/v2/#operation/api.projects.files.get) (response)

**Comment by kisharnath** [comment]
I would like to work on this

**Comment by kisharnath** [comment]
Could you please explain this problem little more?What does it mean by support?

**Comment by andrii-bodnar** [comment]
@kisharnath,

The Crowdin API client provides methods that essentially call Crowdin's APIs.

This makes it much easier for other developers to make calls to Crowdin's APIs, as the client abstracts a lot of the work required.

Feel free to take a look at the existing code. You'll find methods that send a request to various API methods.

In the current case, the new request and response parameters have been added to the existing API endpoint. So just like that, the client needs to add the new parameter support to the endpoints mentioned in the description.

**Comment by andrii-bodnar** [comment]
@kisharnath here is an example of a similar case - https://github.com/crowdin/crowdin-api-client-python/pull/125
