### ISSUE TITLE
translation_status.get_directory_progress not working anymore

### ISSUE THREAD

**Issue by sunny0531** [crowdin/crowdin-api-client-python#14]
It still works until May 31, 
Error:
crowdin_api.exceptions.NotFound: NotFound: http_status=404, request_id=None, detail: None, context=b'{"error":{"message":"Not Found","code":404}}'
Thanks of helping

**Comment by andrii-bodnar** [comment]
Hi @sunny0531,

Could you please provide a part of the code where you making this API request? Thank you

**Comment by sunny0531** [comment]
Which part?
fileprogress=client.translation_status.get_directory_progress(project_id,iiiii["data"]["directoryId"])
Thanks

**Comment by andrii-bodnar** [comment]
@sunny0531 thank you. Could you please share the Project ID to which you are making requests?

**Comment by sunny0531** [comment]
Sorry for late reply, the project id is 442446

**Comment by andrii-bodnar** [comment]
@sunny0531 thanks for the details provided.

It looks like you are making a request to not existing Project ID or Directory ID. please make sure that passed `project_id` is correct and directory with ID `iiiii["data"]["directoryId"]` exists in this project.

**Comment by andrii-bodnar** [comment]
Hi @sunny0531,

we are experiencing some issues with an API method *Export Project Translation* related to the glossary file in the project. Sorry for the inconvenience, we're under investigation of this issue.

**Comment by andrii-bodnar** [comment]
Hi @sunny0531! Somehow missed this issue.

It was already fixed a few weeks ago. Could you please check if everything is ok now?

**Comment by sunny0531** [comment]
I end up using another feature, I will test this when I have time, thanks
