### ISSUE TITLE
Security Logs API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#146]
Crowdin has recently released a new API methods to get information about security logs. It would be great to add support of these methods to the Crowdin API client.

**References:**

- [List User Security Logs](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.getMany)
- [Get User Security Log](https://developer.crowdin.com/api/v2/#operation/api.users.security-logs.get)
- [List Organization Security Logs](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.getMany) (Crowdin Enterprise)
- [Get Organization Security Log](https://developer.crowdin.com/enterprise/api/v2/#operation/api.security-logs.get) (Crowdin Enterprise)

**Comment by OmAximani0** [comment]
Hi @andrii-bodnar , I want to work on this

**Comment by andrii-bodnar** [comment]
Hi @OmAximani0, awesome, thank you!
