### ISSUE TITLE
Tasks API updates

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#152]
Recently, Crowdin introduced the new Sequential Tasks feature, which allows you to instantly create a proofreading task with the same scope.

The Tasks API has been updated: the new forms have been added and the form parameters have been updated. Some were deprecated, we should remove them from the codebase.

**API reference:**

- [Add Task (crowdin.com)](https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post)
- [Add Task (Crowdin Enterprise)](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.tasks.post)

**Comment by Martin005** [comment]
@andrii-bodnar I don't see any way to enable the Sequential tasks neither in the [crowdin.com API docs](https://developer.crowdin.com/api/v2/#operation/api.projects.tasks.post) nor in [Crowdin Enterprise API docs](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.tasks.post).
I only found this [Docs article](https://support.crowdin.com/tasks/#key-approaches) which explains how to do it in the Crowdin UI.

Could you please explain how to enable the creation of the Sequential tasks through the API?
After that, I would like to work on this one, so please assign it to me 🙏

**Comment by andrii-bodnar** [comment]
Hi @Martin005, I just checked the docs and realized that it uses slightly different terminology for some reason. It's a `CrowdinPendingTaskCreateForm`.

<img width="500" alt="Screenshot 2024-11-30 at 11 27 54" src="https://github.com/user-attachments/assets/78dbaf98-6068-4361-a862-7b2bf5b4c035">

At the API level, the approach is a bit different than in the UI. It should be done in two requests - create a Translate task, and create a Pending task by passing the ID (`precedingTaskId`) of the previously created Translate task.
