### ISSUE TITLE
Add new Report Archives API endpoints

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#156]
Crowdin has recently introduced a new feature called _Report Archives_ that allows you to see the history of your reports. This feature comes with a set of new API endpoints that you can use to interact with the report archives.

The new API endpoints should be added to the Crowdin API client.

**References:**
- [List Report Archives](https://developer.crowdin.com/api/v2/#operation/api.reports.archives.getMany)
- [Get Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.get)
- [Delete Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.delete)
- [Export Report Archive](https://developer.crowdin.com/api/v2/#operation/api.reports.archives.exports.post)
- [Check Report Archive Export Status](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.exports.get)
- [Download Report Archive](https://developer.crowdin.com/api/v2/#operation/api.users.reports.archives.exports.download.get)

**Comment by OmAximani0** [comment]
Hi @andrii-bodnar , assign this to me

**Comment by OmAximani0** [comment]
@andrii-bodnar For [List Report Archive](https://developer.crowdin.com/api/v2/#operation/api.reports.archives.getMany) there is no required path parameter mentioned for `userId` in the document but for URL path it is required so how are we planning for it ?

**Comment by andrii-bodnar** [comment]
Hi @OmAximani0, the `userId` path parameter is required for crowdin.com, but not for Crowdin Enterprise (https://developer.crowdin.com/enterprise/api/v2/#operation/api.reports.archives.getMany).

Please make it optional and build the request URL based on the presence of this parameter in the call.

You can check the Java implementation - https://github.com/crowdin/crowdin-api-client-java/pull/242

**Comment by OmAximani0** [comment]
@andrii-bodnar I want to ask that since we have two different resource like `ReportsResource` and `EnterpriseReportsResource` can we directly implement **Reports Archive** into those two classes without any base resource?

**Comment by andrii-bodnar** [comment]
@OmAximani0 yes, there is no need to differentiate these resources at the API client level.
