### ISSUE TITLE
add_concept endpoint missing

### ISSUE THREAD

**Issue by mounan** [crowdin/crowdin-api-client-python#157]
Why isn't there an add_concept endpoint? Do you ignore it on purpose?

_Originally posted by @mounan in https://github.com/crowdin/crowdin-api-client-python/issues/52#issuecomment-2091026146_

**Comment by andrii-bodnar** [comment]
@mounan there is no _Add Concept_ API method in Crowdin.

You're probably looking for the [Add Term](https://developer.crowdin.com/api/v2/#operation/api.glossaries.terms.post) method. It returns the `conceptId` in the response. You can also use this method to add a term to the existing concept (by passing the `conceptId` in the requrst)

**Comment by mounan** [comment]
Sorry, let me clarify the issue. In the web UI, we can create the definition, subject and etc. of a bunch of terms which you call it a concept. But I didn't find the endpoint to create such concept through this client. I thought this client is provided by a crowdin team so you can decide to create any endpoint you want.

**Comment by andrii-bodnar** [comment]
@mounan yes, it is indeed a bit confusing. I just tested it on my end and can confirm that adding a term creates a new concept just like creating a concept via the UI.

**Request and response:**

<img width="654" alt="Screenshot 2024-05-03 at 21 55 01" src="https://github.com/crowdin/crowdin-api-client-python/assets/29282228/43b85910-ef04-472f-b511-0d30cfeeccb2">

**UI:**

<img width="1242" alt="Screenshot 2024-05-03 at 21 59 09" src="https://github.com/crowdin/crowdin-api-client-python/assets/29282228/46a181d4-20dc-40aa-8999-ccbfc99b50e4">
