### ISSUE TITLE
List Terms API: add `croql` parameter support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#182]
The new parameter `croql` should be added to the List Terms API in this client to support the new feature in the Crowdin API.

**References:**

- [List Terms](https://support.crowdin.com/developer/api/v2/#tag/Glossaries/operation/api.glossaries.terms.getMany)

**Comment by imprvhub** [comment]
@andrii-bodnar Can i be assigned to contribute to this issue? Thanks!

**Comment by imprvhub** [comment]
@andrii-bodnar Please disregard commit 03b7b57. The actual implementation of the croql parameter has been submitted in the new commit on the feature/add-croql-parameter branch.
