### ISSUE TITLE
Workflows API: new `List Strings on the Workflow Step` method

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#184]
The Workflows API (Crowdin Enterprise) has a new method to list strings on the workflow step. It should also be added to the Crowdin API clients.

**References:**

- [List Strings on the Workflow Step](https://support.crowdin.com/developer/enterprise/api/v2/#tag/Workflows/operation/api.projects.workflow-steps.strings.getMany)

**Comment by imprvhub** [comment]
Hi! I'd like to work on this issue and implement the List Strings method for the Workflow Step API. Could I be assigned to it?

**Comment by imprvhub** [comment]
Hi @andrii-bodnar - PR is ready for review. Thanks for letting me contribute to this project!
