### ISSUE TITLE
Adding Storage

### ISSUE THREAD

**Issue by AreYSerious** [crowdin/crowdin-api-client-python#21]
Could someone explain to me how to add a file and therefore create storage?
The storage part is where im struggling.

Thanks

**Comment by andrii-bodnar** [comment]
Hi @AreYSerious!

Thanks for the question. We'll definitely add a sample to the Readme.

The following code should work (tested it with a Python 3.9):

```python
from crowdin_api import CrowdinClient

class FirstCrowdinClient(CrowdinClient):
    TOKEN = "<personal_access_token>"

client = FirstCrowdinClient()

file_name = '1.json'

storage = client.storages.add_storage(open(file_name))

my_file = client.source_files.add_file(<crowdin_project_id>, storage['data']['id'], file_name)

print(my_file)
```

Please make sure to replace the `<personal_access_token>` and `<crowdin_project_id>` with the corresponding values.

In this test, the file `1.json` was located in the same directory as my script.

**Comment by AreYSerious** [comment]
Thanks 👍

**Comment by AreYSerious** [comment]
I had to add open the file in binary mode to get it to work...

line 10:

    storage = client.storages.add_storage(open(file_name, 'rb'))

**Comment by andrii-bodnar** [comment]
@AreYSerious, thanks, updated the Readme
