### ISSUE TITLE
PIP version problem: 3.11.1 -> 3.12.0

### ISSUE THREAD

**Issue by alex-flea** [crowdin/crowdin-api-client-python#84]
It seems that there's something broken with PIP as for 3.12.0. Today it just stopped working.

`crowdin upload sources`

Produces next warning:

> New version of Crowdin CLI is available! 3.11.1 -> 3.12.0

And then an error:

> crowdin_api.exceptions.ValidationError: ValidationError: http_status=400, request_id=None, detail: None, context=b'{"error":{"message":"Incorrect json in request body. No error","code":400}}'

However, when trying to execute

```
pip install crowdin-api-client --upgrade --user
```

It stays on 3.11.1 with the next output:

```
pip install crowdin-api-client --upgrade --user
Requirement already satisfied: crowdin-api-client in /home/ci/.local/lib/python3.11/site-packages (1.10.0)
Requirement already satisfied: requests>=2.25.1 in /usr/lib/python3.11/site-packages (from crowdin-api-client) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests>=2.25.1->crowdin-api-client) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests>=2.25.1->crowdin-api-client) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests>=2.25.1->crowdin-api-client) (1.26.12)
```

**Comment by Oppai-Man** [comment]
I'm also getting the same error message in all my requests, even a simple

`client.projects.list_projects()`

Returns that error message.

**Comment by dem214** [comment]
There problem is that the client sends "null" in body on GET requests. it used to be OK, but now API changed and response with 400 bad request. Seems like a bug and need to be fixed asap.

https://github.com/crowdin/crowdin-api-client-python/blob/81e43ef9139b8acbe7c2d2b6e0c915927e4e0e7b/crowdin_api/requester.py#L118
