### ISSUE TITLE
Strings Exporter Settings API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-python#99]
Crowdin recently added a bunch of new API methods to manage Strings Exporter settings for some file formats.

The new methods need to be added to this API Client.

**API Reference:**

- [List Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.getMany)
- [Add Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.post)
- [Get Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.get)
- [Delete Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.delete)
- [Edit Project Strings Exporter Settings](https://developer.crowdin.com/api/v2/#operation/api.projects.strings-exporter-settings.patch)

**Comment by OmAximani0** [comment]
Hi @andrii-bodnar , I want to work on this. Can you please guide me through ?

**Comment by andrii-bodnar** [comment]
Hi @OmAximani0, sure, thank you!

**Comment by OmAximani0** [comment]
For type `XliffStringsExporterSettings`

![image](https://github.com/crowdin/crowdin-api-client-python/assets/75031769/fbd6566b-e83f-4269-bd8c-2ff45428592d)

is this a valid type ?
```python
class XliffStringsExporterSettings(TypedDict):
    languagePairMapping: Dict[str, str]

```

**Comment by andrii-bodnar** [comment]
@OmAximani0 yes, this is correct type

**Comment by OmAximani0** [comment]
> @OmAximani0 yes, this is correct type

Ok, Thank you @andrii-bodnar
